// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	models "miniproject/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// FoodRepository is an autogenerated mock type for the FoodRepository type
type FoodRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: foodUc
func (_m *FoodRepository) Create(foodUc models.Food) error {
	ret := _m.Mock.Called(foodUc)

	return ret.Error(0)


}

// Delete provides a mock function with given fields: id
func (_m *FoodRepository) Delete(id string) error {
	ret := _m.Mock.Called(id)

	return ret.Error(0)
}

// FindAll provides a mock function with given fields:
func (_m *FoodRepository) FindAll() ([]models.Food, error) {
	ret := _m.Mock.Called()


	return ret.Get(0).([]models.Food), ret.Error(1)
}

// FindById provides a mock function with given fields: id
func (_m *FoodRepository) FindById(id string) (*models.Food, error) {
	ret := _m.Mock.Called(id)


	return ret.Get(0).(*models.Food),ret.Error(1)
}

// Update provides a mock function with given fields: id, foodUc
func (_m *FoodRepository) Update(id string, foodUc models.Food) error {
	ret := _m.Mock.Called(id, foodUc)

	return ret.Error(0)
}


